### ISSUE TITLE
should we round very small compartment values?

### ISSUE THREAD

**Issue by kerklohlaurin** [DLR-SC/ESID#177] opened 2022-09-26 13:05 UTC
![grafik](https://user-images.githubusercontent.com/101645686/192283866-0f2603c2-3bd7-491a-9814-2d96e9bca86b.png)

**Comment by kerklohlaurin** [comment] 2022-09-26 13:06
related to #171

**Comment by JonasGilg** [comment] 2022-10-07 12:33
Closed, because duplicate of #171.

**Closed by JonasGilg** 2022-10-07 12:33 UTC
Labels: help wanted, question
